version: "3.3"
services:
  database:
    image: starsky_postgres
    build:
      context: .
      dockerfile: src/com/starsky/database/Dockerfile
    environment:
      - POSTGRES_USER=starsky
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    network_mode: "host"
    container_name: starsky_db
  api:
    image: starsky_jdk
    build:
      context: .
      dockerfile: src/com/starsky/api/Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - STARSKY_JWT_SECRET=${STARSKY_JWT_SECRET}
      - STARSKY_ENVIRONMENT=${STARSKY_ENVIRONMENT}
    ports:
      - "8080:8080"
    network_mode: "host"
    container_name: starsky_api