version: "3.3"
services:
  database:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
  api:
    image: peroxy12/starsky-backend-api:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - STARSKY_JWT_SECRET=${STARSKY_JWT_SECRET}
    restart: always
  nginx:
    image: nginx:1.19.7-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - /nginx/conf.d/api.conf:/etc/nginx/conf.d/api.conf
    depends_on:
      - api