version: "3.3"
services:
  database:
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    network_mode: "host"
  api:
    build:
      context: ../.
      dockerfile: api/Dockerfile
    ports:
      - 8080:8080
    container_name: starsky_backend_api
    restart: on-failure
    depends_on:
      - database
    network_mode: host
