version: "3.3"
services:
  database:
    environment:
      - POSTGRES_USER=starsky
      - POSTGRES_PASSWORD=starsky
  api:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - POSTGRES_USER=starsky
      - POSTGRES_PASSWORD=starsky