version: "3.8"
services:
  database:
    environment:
      - POSTGRES_USER=starsky
      - POSTGRES_PASSWORD=starsky
  api:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - POSTGRES_USER=starsky
      - POSTGRES_PASSWORD=starsky
      - STARSKY_JWT_SECRET=starsky