version: "3.3"
services:
  database:
    image: starsky_postgres
    build:
      context: .
      dockerfile: database/Dockerfile
    environment:
      - POSTGRES_USER=starsky
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    network_mode: "host"
    container_name: starsky_db
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile-api
#    environment:
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    ports:
#      - "61234:61234"
#    network_mode: "host"
#    restart: on-failure
# todo: depends on??? multi stage?